# Use Node.js image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy dependencies files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the project
COPY . .

# Include environment file
COPY .env .env

# Run the build process
RUN npm run build

# Expose the port your app runs on
EXPOSE 9702

# Start the app
CMD ["npm", "run", "preview"]
